# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e35eb1ffb7ebc2bdb29e2676b85cd4be6385c2b31b141cf9f70f62049123c89303940cebc2734fd9fcf25c056bdafbdba8ed57aa49758d70a2a9746013beef72

test:
  secret_key_base: 5ce01a3fcbb4fcfe6e4e4b442d2503db1e360eee54f09bfffdf0cd82ceccbba5e11b4b48523ba46f6ed47b81fc1f06a6fbaa43117de8fd26315dfaf8929cfb91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
